// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoXa8t8p229uojlxPJfwnua0DKCqcG-_g',
    appId: '1:331630389707:web:9d64a62182c0e88e912e4e',
    messagingSenderId: '331630389707',
    projectId: 'loginteste-cafe5',
    authDomain: 'loginteste-cafe5.firebaseapp.com',
    storageBucket: 'loginteste-cafe5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFAUEkq6rpzUelb4Dqn3cq5Jy8Dq_koAg',
    appId: '1:331630389707:android:f17b87629bb50f97912e4e',
    messagingSenderId: '331630389707',
    projectId: 'loginteste-cafe5',
    storageBucket: 'loginteste-cafe5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQqppFsiM-N5K9nYEXcXNeKtMM63xRZFM',
    appId: '1:331630389707:ios:d2d04ed3f32cd089912e4e',
    messagingSenderId: '331630389707',
    projectId: 'loginteste-cafe5',
    storageBucket: 'loginteste-cafe5.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQqppFsiM-N5K9nYEXcXNeKtMM63xRZFM',
    appId: '1:331630389707:ios:a27b856c4af01a87912e4e',
    messagingSenderId: '331630389707',
    projectId: 'loginteste-cafe5',
    storageBucket: 'loginteste-cafe5.appspot.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
